name: Revert Pull Request Approve

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        type: string
env:
  ORG: masartz
  REPOS: test_repository

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.REVERT_APPROVE_APP_ID }}
          private-key: ${{ secrets.REVERT_APPROVE_PRIVATE_KEY }}
      - name: Fetch Pull Request Metadata
        id: fetch_pr
        run: |
          pr_number=${{ github.event.inputs.pr_number }}
          response=$(curl -s -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
                             -H "Accept: application/vnd.github.v3+json" \
                             https://api.github.com/repos/${{ env.ORG }}/${{ env.REPOS }}/pulls/$pr_number)
          pr_title=$(echo "$response" | jq -r '.title')
          echo "pr_title=$pr_title" >> $GITHUB_OUTPUT

      - name: Is PR Reverted
        id: is-reverted
        run: |
          title='${{ steps.fetch_pr.outputs.pr_title }}'
          pattern='^Revert ".*"'
          if [[ $title =~ $pattern ]]; then
            echo "true"
            echo "is-reverted=true" >> $GITHUB_OUTPUT
          else
            echo "false"
          fi

      - name: Approve PR
        if: steps.is-reverted.outputs.is-reverted == 'true'
        run: |
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: "https://github.com/${{ env.ORG }}/${{ env.REPOS }}/pull/${{github.event.inputs.pr_number}}"
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
