name: Revert Pull Request Approve

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        type: string
env:
  ORG: masartz
  REPOS: test_repository

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.REVERT_APPROVE_APP_ID }}
          private-key: ${{ secrets.REVERT_APPROVE_PRIVATE_KEY }}
      - name: Fetch Pull Request Metadata
        id: fetch_pr
        run: |
          pr_number=${{ github.event.inputs.pr_number }}
          response=$(gh pr view --json title,author $pr_number)
          pr_title=$(echo "$response" | jq -r '.title')
          pr_author=$(echo "$response" | jq -r '.author.name')
          echo "pr_title=$pr_title" >> $GITHUB_OUTPUT
          echo "pr_author=$pr_author" >> $GITHUB_OUTPUT
        env:
          GH_REPO: ${{ env.ORG }}/${{ env.REPOS }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Is PR Reverted
        id: is-reverted
        run: |
          title='${{ steps.fetch_pr.outputs.pr_title }}'
          pattern='^Revert ".*"'
          if [[ $title =~ $pattern ]]; then
            echo "true"
            echo "is-reverted=true" >> $GITHUB_OUTPUT
          else
            echo "false"
          fi
      - name: Is PR Created by Actor
        id: is-created-by-actor
        run: |
          pr_author='${{ steps.fetch_pr.outputs.pr_author }}'
          actor='${{ github.actor }}'
          if [[ $actor == $pr_author ]]; then
            echo "true"
            echo "is-created-by-actor=true" >> $GITHUB_OUTPUT
          else
            echo "false"
          fi

      - name: Approve PR
        if: steps.is-reverted.outputs.is-reverted == 'true' && steps.is-created-by-actor.outputs.is-created-by-actor == 'true'
        run: |
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: "https://github.com/${{ env.ORG }}/${{ env.REPOS }}/pull/${{github.event.inputs.pr_number}}"
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
