# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths: "test.yaml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: checkout "${{ github.head_ref }}"
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref}}
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: get name
        run: echo "${{ github.event.pusher.name }} ${{ github.event.head_commit.url }} ${{ github.event_name }} " 
      - name: get-diff
        uses: gh640/command-result-action@v1
        with:
          command: git diff -U0 HEAD~
        id: get-diff
      - name: get-change
        uses: gh640/command-result-action@v1
        with:
          command: echo ${{ steps.get-diff.outputs.stdout }} | grep '^+' | grep -Ev '^\+\+\+ b/' | sed 's/^+//'
        id: get-change
      - name: cat
        run: cat $GITHUB_EVENT_PATH
      - name: slack-send
        uses: slackapi/slack-github-action@v1.25.0
        with:
        # For posting a rich message using Block Kit
          payload: |
            {
              "text": "yaml updated",
              "blocks": [
                {
                  "author": "${{ github.event.pusher.name }}",
                  "commit": "${{ github.event.head_commit.url }}",
                  "diff": "${{ steps.get-change.outputs.stdout }}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
            
